//canvas
const game = document.querySelector('#game');
const computedStyle = getComputedStyle(game);
const height =computedStyle.height
const width = computedStyle.width

///STATUS VARIABLES/
let gameStatus = 'gameOver'//defines if the games is runni
let gameWon = false;
let crazyStatus = false; //randomly turns black car 1 into a grey car
let crazyStatus2 = false;//used for other cars to keep them in the same state
let carHit = true;//tracks collisions
let sugoi = false;//tracks when a grey car is bumped off the road to trigger point accumulation and pop up art
let car2enter = false; // used to wait for car2 to enter the sreen at the sart of the ga,e
let car3enter = false;
let paused = false; // used to pause the game
let playMuisc = 0;// used to paly music only once 


//COUNTERS///
let counter = 0;//for road animation
let carOneCounter = 0;// sets counter to move oncoming car 1
let carTwoCounter =0;//
let carThreeCounter = 0;
let pointAccumulator = 0;//accumulates game points


//sets a counter to run road lane animation
var line1 = document.getElementById("game");
let crazyIndex;
var ctx = line1.getContext("2d");
//DEFAULTS
const laneDefault = 38;// coorinates of our first lane
const laneGap = 75;//space between our lanes
const pointAccumulatorDefault = 0;
const setPointAmount = 3000;// the amount of points we want to reach to win the game
const oneWin = 150; // points accumulated at one time
const step = 20;// sets step for user movement
const carRange = 380;// set visible range for cars 
const fieldHeight = 300;// height of our canvas
const fieldWidth = 300//width of our canvas
//CAR MOVEMENT////
let carOne;// will host value of class objects generated by the game
let carTwo;
let carThree;
let carStep = 4;// default car speen in pixels
const carStepDefault = 4;
let carImage = otherCarImages;// resets BOT cars back to black

//STEPS
const laneChoicesDefault = [38, 38+laneGap, 38+(laneGap*2), 38+ (laneGap*3)]
let laneChoices = [38, 38+laneGap, 38+(laneGap*2), 38+ (laneGap*3)]
let lane = 38;// sets property for car lane coordinates
let lane2 = 38;
let lane3 = 38;



// CLASS OBJECTS!!!

class Car {
    constructor(centerX, centerY, status, image) {
        this.x = centerX-20;
        this.y = centerY -15;
        this.width = 40;
        this.height = 40;
        this.crazyDriver = status;
        this.image = image;
        this.live = carHit;
     }render(){
        const x = this.x;
        const y = this.y;
        const w = this.width;
        const h = this.height;
        const img = new Image();
        img.onload = draw;
        img.src = this.image;
        function draw() {
        const ctx = document.querySelector('canvas').getContext('2d');
        ctx.drawImage(img, x, y, w, h);
        }
        draw();
     }
}; 

function sound(src, repeat) {
    this.sound = document.createElement("audio");
    this.sound.src = src;
    this.sound.setAttribute("preload", "auto");
    this.sound.setAttribute("controls", "none");
    this.sound.style.display = "none";
    document.body.appendChild(this.sound);
    this.play = function(){
      this.sound.play();
      this.sound.addEventListener('ended', function() {
          if(repeat === 'yes'){
            this.currentTime = 0;
            this.play();
          }
        
    }, false);
    }
    
  }

  

  carCrashSound = new sound(carCrashPath, 'no');
  cityPop = new sound(gameMusic, 'yes');
  pointSounds = new sound(pointSound,'no');

const userCar = new Car(150,274, crazyStatus, userCarImage);

//DOM elements
const blob =document.getElementById('blob');//katakana div
const mangaMessage = document.getElementById('message');
const terebi = document.getElementById('terebi');
const cheers = document.getElementById('cheers');
const speil = document.getElementById('speil');
const racerQuote = document.getElementById('racequote');
const pointsDisplay = document.getElementById('points');
const instructionsOneDisplay = document.getElementById('instructions');
const instructionsTwoDisplay = document.getElementById('instructions2');
const pointTracker = document.getElementById('point-tracker');